### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by drews256** [epsilonorion/roscopter#6]
I am pretty new to this so bare with me. While trying to build roscopter I am following instructions on the wiki and I get to the catkin_make part and when I try to run it I get this error. 

The specified base path "/home/ark/roscopter" contains a CMakeLists.txt but "catkin_make" must be invoked in the root of workspace

Can anyone kindly help me out? 

I've tried building the mavlink folder in the src folder like someone did in another issue. But I have the same result.

**Comment by lanyusea** [comment]
Did you create the catkin workspace first before building the package?

**Comment by lanyusea** [comment]
Follow the [wiki](http://wiki.ros.org/catkin/Tutorials/create_a_workspace) to create a workspace first.

Then git co the repo

Then catkin_make.

It should works well.

Remember,
catkin_init_workspace should run under ../workspace/src; 
while catkin_make should run under ../workspce

**Comment by drews256** [comment]
Still no driver.py.

When I try to run it with the roscopter.py it tells me there is no roscopter.msg.

**Comment by lanyusea** [comment]
@drews256  let's do this one by one.
1. your building is successful, right?
2. what command do you use to rosrun? roscopter.py or driver.py?
   what is the error message in terminal?

**Comment by drews256** [comment]
Someone should remove the google code documentation. It is old. Or at least this repository is more robust and includes the files that keep erroring out. 
@lanyusea  

Sorry to get ahead of myself. The build was successful but I was pulling the old roscopter directory on the google code website. Let me try it by pulling the correct directory.

**Comment by lanyusea** [comment]
@drews256  just use this github repo, which was modified and works well, the original one on google code... eh... I'm afraid it is out of maintance.

also the [wiki](https://github.com/epsilonorion/roscopter/wiki#Building) of this repo

**Comment by drews256** [comment]
Yep. I was following instructions on the GitHub wiki and checking out the google code. Now the build is successful. And when I go to start up the topic and again it gives me an error:

Traceback (most recent call last):
  File "/home/ark/catkin_ws/src/roscopter/scripts/driver.py", line 6, in <module>
    import roscopter.msg
ImportError: No module named msg

Looking at the driver.py it also calls a roscopter.srv that isn't in the srv folder. Is this because the build failed?

**Comment by lanyusea** [comment]
nope. the building is successful but you cannot run it.

It seems u meet the same problem as me, check this see if it works:

[import issue](https://github.com/epsilonorion/roscopter/issues/3)

besides this:
1. I suggest you checkout the code on github, I'm not sure whether the code on google suppot groovy or hydro…
2. post your terminal information when asking issues. just copy and paste is OK. knowing what command you run and what the error msgwill make it much better for others to understand your problem, we cannot make sure what's going on just according to your description.
3. roscopter.msg and roscopter.srv are not two files.
   it means two paths: /roscopter/msg and /roscopter/srv
   Googlr "python import from file" if you want to know more.

I need to sleep now… zzz… good luck!

**Comment by tonybaltovski** [comment]
The code works fine on ROS Hydro, that is what I am using. Everything works perfect when I clone and use catkin_make.  Is your ROS environment setup?  Are you cloning the right branch for your version of ROS?

**Comment by drews256** [comment]
@tonybaltovski  I am cloning the Groovy branch and trying to install on Hydro. Seemed to have worked for you. Still getting the same problem. I basically started from scratch trying to make it work. 

@lanyusea I see you have basically the same problem that I did. But I never ran `sudo python setup.py install` just a `catkin_make.`

``````
ark@ark-Vostro-3560:~/catkin_ws$   rosrun roscopter driver.py --device=/dev/ttyUSB0 --baudrate=115200
Traceback (most recent call last):
  File "/home/ark/catkin_ws/src/roscopter/scripts/driver.py", line 6, in <module>
    import roscopter.msg
ImportError: No module named msg
ark@ark-Vostro-3560:~/catkin_ws$ ```

I got it to work once where it was waiting for the heartbeat. After I built it for the first time. But then I closed it and retried after I had plugged everything back in and I got the above message. Seems weird that it worked and then didn't work. 
``````

**Comment by tonybaltovski** [comment]
@drews256 you need to install mavlink as stated in the wiki and then use catkin_make

**Comment by lanyusea** [comment]
@drews256 did you check the import path in python, is it correct?

@tonybaltovski I don't think that's an issue with ROS or mavlink, it should be the problem of python

**Comment by drews256** [comment]
@lanyusea I hate to say it but how do you check the import path in python? Following the other issue you that you had I went to see if there was in fact a `usr/local/lib/python2.7/dist-packages/roscopter` folder. There was a roscopter folder there. I have since deleted it and tried to use `catkin_make` again in `catkin_ws` still no success. The same error. 

@tonybaltovski I am with Ianyusea on this one. I have mavlink in the roscopter folder, the newest version, should I not run a `sudo python setup.py install` after putting it in the roscopter directory?

**Comment by lanyusea** [comment]
@drews256 you mean this time there is a building error instead of the running issue?

The way is typing `python` in ur terminal under workspace,
then

``` python
Python 2.7.4 (default, Sep 26 2013, 03:20:26) 
[GCC 4.7.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import roscopter
>>> import os
>>> os.path.abspath(roscopter.__file__)
```

and check the result

**Comment by drews256** [comment]
@lanyusea  and @tonybaltovski  here is the result from the build. Looks successful to me.

```
ark@ark-Vostro-3560:~/catkin_ws$ catkin_make
Base path: /home/ark/catkin_ws
Source space: /home/ark/catkin_ws/src
Build space: /home/ark/catkin_ws/build
Devel space: /home/ark/catkin_ws/devel
Install space: /home/ark/catkin_ws/install
####
#### Running command: "cmake /home/ark/catkin_ws/src -DCATKIN_DEVEL_PREFIX=/home/ark/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/home/ark/catkin_ws/install" in "/home/ark/catkin_ws/build"
####
-- Using CATKIN_DEVEL_PREFIX: /home/ark/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/hydro
-- This workspace overlays: /opt/ros/hydro
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Python version: 2.7
-- Using Debian Python package layout
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/ark/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- catkin 0.5.86
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - roscopter
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'roscopter'
-- ==> add_subdirectory(roscopter)
-- Using these message generators: gencpp;genlisp;genpy
-- roscopter: 13 messages, 4 services
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ark/catkin_ws/build
####
#### Running command: "make -j4 -l4" in "/home/ark/catkin_ws/build"
####
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_py
[  1%] [  3%] Generating Lisp code from roscopter/WaypointList.msg
[  5%] Generating Lisp code from roscopter/ControllerOutput.msg
[  7%] Generating C++ code from roscopter/WaypointList.msg
Generating Python from MSG roscopter/WaypointList
[  9%] Generating Lisp code from roscopter/Mavlink_RAW_IMU.msg
[ 11%] Generating Lisp code from roscopter/FilteredPosition.msg
[ 13%] Generating Python from MSG roscopter/ControllerOutput
[ 15%] Generating Python from MSG roscopter/Mavlink_RAW_IMU
[ 16%] [ 18%] Generating Python from MSG roscopter/FilteredPosition
Generating Lisp code from roscopter/State.msg
[ 20%] Generating C++ code from roscopter/ControllerOutput.msg
[ 22%] Generating Lisp code from roscopter/Waypoint.msg
[ 24%] Generating Python from MSG roscopter/State
[ 26%] Generating C++ code from roscopter/Mavlink_RAW_IMU.msg
[ 28%] Generating Lisp code from roscopter/CurrentMission.msg
[ 30%] Generating Python from MSG roscopter/Waypoint
[ 32%] Generating Lisp code from roscopter/Control.msg
[ 33%] Generating Python from MSG roscopter/CurrentMission
[ 35%] Generating Lisp code from roscopter/Status.msg
[ 37%] Generating Lisp code from roscopter/VFR_HUD.msg
[ 39%] Generating Python from MSG roscopter/Control
[ 41%] [ 43%] Generating C++ code from roscopter/FilteredPosition.msg
Generating Lisp code from roscopter/MissionItem.msg
[ 45%] Generating C++ code from roscopter/State.msg
[ 47%] Generating Python from MSG roscopter/Status
[ 49%] Generating Lisp code from roscopter/Attitude.msg
[ 50%] Generating Python from MSG roscopter/VFR_HUD
[ 52%] Generating Lisp code from roscopter/RC.msg
[ 54%] Generating C++ code from roscopter/Waypoint.msg
[ 56%] Generating Python from MSG roscopter/MissionItem
[ 58%] Generating C++ code from roscopter/CurrentMission.msg
[ 60%] Generating Lisp code from roscopter/SendWaypoint.srv
[ 62%] Generating Python from MSG roscopter/Attitude
[ 64%] Generating Lisp code from roscopter/APMCommand.srv
[ 66%] Generating Python from MSG roscopter/RC
[ 67%] Generating Lisp code from roscopter/XBEECommand.srv
[ 69%] [ 71%] Generating Lisp code from roscopter/SendWaypointList.srv
Generating C++ code from roscopter/Control.msg
[ 73%] Generating Python code from SRV roscopter/SendWaypoint
[ 75%] Generating C++ code from roscopter/Status.msg
[ 75%] Built target roscopter_generate_messages_lisp
[ 77%] Generating C++ code from roscopter/VFR_HUD.msg
[ 79%] Generating Python code from SRV roscopter/APMCommand
[ 81%] Generating Python code from SRV roscopter/XBEECommand
[ 83%] Generating C++ code from roscopter/MissionItem.msg
[ 84%] Generating C++ code from roscopter/Attitude.msg
[ 86%] Generating Python code from SRV roscopter/SendWaypointList
[ 88%] Generating C++ code from roscopter/RC.msg
[ 90%] Generating Python msg __init__.py for roscopter
[ 92%] [ 94%] Generating Python srv __init__.py for roscopter
Generating C++ code from roscopter/SendWaypoint.srv
[ 96%] Generating C++ code from roscopter/APMCommand.srv
[ 98%] [ 98%] Built target roscopter_generate_messages_py
[100%] Generating C++ code from roscopter/XBEECommand.srv
Generating C++ code from roscopter/SendWaypointList.srv
[100%] Built target roscopter_generate_messages_cpp
[100%] Built target roscopter_generate_messages
ark@ark-Vostro-3560:~/catkin_ws$  rosrun roscopter driver.py --device=/dev/ttyUSB0 --baudrate=115200
Traceback (most recent call last):
  File "/home/ark/catkin_ws/src/roscopter/scripts/driver.py", line 6, in <module>
    import roscopter.msg
ImportError: No module named roscopter.msg
```

**Comment by drews256** [comment]
@lanyusea Here is the result of the python check. I didn't get very far. 

```
Python 2.7.3 (default, Feb 27 2014, 20:00:17) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import roscopter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named roscopter
```

**Comment by lanyusea** [comment]
@drews256  I think you should did this but I want to ask again:
did you source the workspace in your .bashrc file?
i.e. put a line like that `source ~/ros_catkin/devel/setup.bashrc`

`source .bashrc` then have a try.

because according to 

```
[ 90%] Generating Python msg __init__.py for roscopter
[ 92%] [ 94%] Generating Python srv __init__.py for roscopter
```

the path should be workthroughed successfully.

is there a `__init__.py` and  `__init__.pyc`
in path `devel/lib/python2.7/dist-packages/roscopter`?

**Comment by drews256** [comment]
Alright issue fixed. I moved my catkin_ws to a more convenient location but never sourced the setup.bashrc. Thank you @lanyusea for helping me look down that road. After adding a line and running it again it worked. I tried it again to make sure and it worked again. That you so much for your help @lanyusea and @tonybaltovski

**Comment by lanyusea** [comment]
@drews256  you're welcome and glad to see it finally works  )

seems issue can be close

**Comment by epsilonorion** [comment]
Sorry I just got in here and saw the issues you guys were having.  I have some free time now so I will work on updating the wiki a little more to make it more concise and easier. Let me know if there is anything specific you feel would be helpful.
